# Generated by Django 3.2.8 on 2021-10-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projets',
            new_name='Projet',
        ),
    ]
