# Generated by Django 3.2.8 on 2021-10-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_tracking', '0002_rename_projets_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('F', 'FAIBLE'), ('M', 'MOYENNE'), ('E', 'ELEVEE')], max_length=50)),
                ('balise', models.CharField(choices=[('BUG', 'BUG'), ('AMELIORATION', 'AMELIORATION'), ('TACHE', 'TACHE')], max_length=50)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'A faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
