# Generated by Django 3.2.8 on 2021-10-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_tracking', '0004_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(max_length=6000),
        ),
    ]
