# Generated by Django 3.2.8 on 2021-10-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_tracking', '0005_alter_projet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(),
        ),
    ]
