# Generated by Django 3.2.8 on 2021-10-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem_tracking', '0006_alter_projet_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='Description',
            new_name='description',
        ),
    ]
