# Generated by Django 3.2.8 on 2021-10-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem_tracking', '0008_probleme_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='probleme',
            old_name='project',
            new_name='projet',
        ),
    ]
