# Generated by Django 3.2.8 on 2021-10-29 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem_tracking', '0011_auto_20211029_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleme',
            name='assigne',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='problemes', to=settings.AUTH_USER_MODEL),
        ),
    ]
