# Generated by Django 3.2.8 on 2021-11-05 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem_tracking', '0013_auto_20211029_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('auteur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('F', 'FAIBLE'), ('M', 'MOYENNE'), ('E', 'ELEVEE')], max_length=50)),
                ('balise', models.CharField(choices=[('BUG', 'BUG'), ('AMELIORATION', 'AMELIORATION'), ('TACHE', 'TACHE')], max_length=50)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'A faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assigne', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('BE', 'Back-end'), ('FE', 'Front-end'), ('IOS', 'IOS'), ('AND', 'Android')], max_length=30)),
                ('auteur', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='probleme',
            name='assigne',
        ),
        migrations.RemoveField(
            model_name='probleme',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='auteur',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='Probleme',
        ),
        migrations.DeleteModel(
            name='Projet',
        ),
        migrations.AddField(
            model_name='issue',
            name='projet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='problem_tracking.project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='probleme',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='problem_tracking.issue'),
        ),
    ]
