# Generated by Django 3.2.8 on 2021-11-05 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem_tracking', '0014_auto_20211105_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[], max_length=50)),
                ('role', models.CharField(choices=[('AUTHOR', 'Auteur'), ('MANAGER', 'Responsable'), ('CREATOR', 'Créateur')], max_length=50)),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='problem_tracking.project')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
