# Generated by Django 3.2.8 on 2021-11-17 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem_tracking', '0016_comment_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues_auteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigne',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues_assigne', to=settings.AUTH_USER_MODEL),
        ),
    ]
