# Generated by Django 3.2.8 on 2021-12-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_tracking', '0018_auto_20211117_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('ALL', 'All Permissions')], max_length=50),
        ),
    ]
